ev:
  uploadPath: D:/var/uploaded_files/
  excelPath: D:/var/excel_files/
logging:
  level:
    root: info
    com.bootdo: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinsoft-gyhl?useUnicode=true&characterEncoding=utf8
    username: xinsoft
    password: xinsoft411
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    host: localhost
    port: 6379
    password: 1q2w3e4r!@#$
    # 连接超时时间（毫秒）
    timeout: 10000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
  influx:
    url: http://localhost:8086
    user: xinsoft
    password: xinsoft
    database: sentinel_log
    rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: admin
      listener:
        simple:
          #acknowledge-mode: auto
          concurrency: 10
          max-concurrency: 50
          retry:
            enabled: true
          prefetch: 5
feign:
  hystrix:
    enabled: false

org:
  ftp:
    address: 120.132.17.116
    port: 2121
    userName: ftpuser
    password: 1q2w3e4r!@
    basePath: gyhl-file
    localPath: C:\ftp

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #是否开启超时熔断
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 10000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1
upload:
  config:
    path: D:/Program Files/jenkins/workspace/gyhl-local-zd/target/classes/fdfs_client.conf
wechat:
  agentid: 1000002
  corpid: wwe26901b80e14be58
  corpsecret: 5uBcZkFHpkwNMq12_opCFLujeKFeK-lSAqaoXcjTOcE
  mobilesecret: E75EzVpoDuBleILD7LRfENENWgH7j-rzbUTToL52avE
  appurl: http://120.132.17.116:18090/gyhl-app/#/pages
